export const LABELS = {
  COMMON: {
    LOADING: 'Loading…',
    BACK: 'Back',
    CANCEL: 'Cancel',
    OVERVIEW: 'Overview',
    ALL_RESOURCES: 'All resources',
  },
  RESOURCES_LIST: {
    TITLE: 'Resources',
    SUBTITLE: 'Create resources and track module progress through provisioning.',
    CREATE_SECTION: 'New resource',
    LIST_SECTION: 'Your resources',
    CREATE_BUTTON: 'Create',
    CREATING: 'Creating…',
    OPEN_OVERVIEW: 'Open',
    DELETE: 'Delete',
    DELETING: 'Deleting…',
    DELETE_DIALOG_TITLE: 'Delete resource?',
    DELETE_DIALOG_MESSAGE: (name: string) =>
      `"${name}" will be permanently deleted.`,
    LOADING: 'Loading resources…',
    EMPTY: 'No resources yet.',
    EMPTY_DRAFTS: 'No draft resources on this page.',
    FILTER_DRAFTS_ONLY: 'Show draft resources only',
    MODULES_NOT_STARTED: 'Start with Basic Info, then Project Details.',
    MODULES_ONE_LEFT: 'One module left before you can complete this resource.',
    META_SEPARATOR: '·',
    NAME_PLACEHOLDER: 'e.g. onboarding-flow',
    NAME_HELPER: 'Letters, numbers, spaces, and hyphens. Max 255 characters.',
    RESOURCE_NAME: 'Name',
    PAGINATION_PREVIOUS: 'Previous',
    PAGINATION_NEXT: 'Next',
    PAGINATION_SUMMARY: (page: number, totalPages: number, totalItems: number) =>
      `Page ${page} of ${totalPages} (${totalItems} total)`,
  },
  OVERVIEW: {
    TITLE: 'Overview',
    SUBTITLE: 'Module progress and provisioning.',
    VIEW_DETAILS: 'Details',
    RESOURCE_ID: 'ID',
    BUFFER_ACTIVE: 'Unsaved changes',
    PROVISIONING: 'Provisioning',
    PROVISIONING_DESCRIPTION:
      'Moves a draft resource to completed when both modules are complete.',
    ALREADY_COMPLETED: 'Already completed.',
    PROVISION: 'Complete resource',
    PROVISIONING_IN_PROGRESS: 'Completing…',
  },
  DETAILS: {
    TITLE: 'Details',
    SUBTITLE: 'Summary of both modules.',
    BACK_TO_OVERVIEW: 'Back to overview',
    BUFFER_NOTE: 'Includes unsaved changes',
  },
  MODULE: {
    BASIC_INFO: 'Basic Info',
    PROJECT_DETAILS: 'Project Details',
    BASIC_INFO_DESCRIPTION: 'Owner, contact, and priority.',
    PROJECT_DETAILS_DESCRIPTION: 'Project scope and team.',
    LOCKED_REASON: 'Complete Basic Info first',
    REVIEW_EDIT: 'Edit',
    CONTINUE: 'Continue',
    LOCKED: 'Locked',
  },
  STATUS: {
    COMPLETE: 'Complete',
    INCOMPLETE: 'Incomplete',
    DRAFT: 'Draft',
    COMPLETED: 'Completed',
  },
  FORM: {
    SAVE_MODULE: 'Save',
    SUBMIT_CHANGES: 'Submit',
    SAVING: 'Saving…',
    BUFFER_NOTICE: 'Changes are saved locally until you submit. They are lost on refresh.',
    DRAFT_BASIC_INFO_SUBTITLE: 'Fill in all fields to unlock Project Details.',
    COMPLETED_EDIT_SUBTITLE: 'Submit to save changes to the server.',
    PROJECT_DETAILS_DRAFT_SUBTITLE: 'Complete Basic Info first.',
    PROJECT_DETAILS_LOCKED_NOTICE: 'Complete Basic Info before editing this module.',
    RESOURCE_NAME_LOCKED: 'Cannot be changed after creation.',
    OWNER_HELPER: 'Letters and spaces only.',
    BUDGET_HELPER: 'Whole numbers only.',
    TEAM_MEMBERS_HELPER: 'Select at least one.',
    SELECT_PRIORITY: 'Select priority',
    SELECT_CATEGORY: 'Select category',
    FIELDS: {
      RESOURCE_NAME: 'Resource name',
      OWNER: 'Owner',
      EMAIL: 'Email',
      DESCRIPTION: 'Description',
      PRIORITY: 'Priority',
      PROJECT_NAME: 'Project name',
      BUDGET: 'Budget',
      CATEGORY: 'Category',
      TEAM_MEMBERS: 'Team members',
    },
  },
  VALIDATION: {
    RESOURCE_NAME_REQUIRED: 'Resource name is required.',
    RESOURCE_NAME_MAX: 'Resource name must be 255 characters or fewer.',
    RESOURCE_NAME_FORMAT: 'Resource name can only contain letters, numbers, spaces, and hyphens.',
    OWNER_REQUIRED: 'Owner is required.',
    OWNER_MAX: 'Owner must be 255 characters or fewer.',
    OWNER_FORMAT: 'Owner can only contain letters and spaces.',
    EMAIL_REQUIRED: 'Email is required.',
    EMAIL_FORMAT: 'Enter a valid email address.',
    DESCRIPTION_REQUIRED: 'Description is required.',
    DESCRIPTION_MAX: 'Description must be 1000 characters or fewer.',
    PRIORITY_REQUIRED: 'Select a priority.',
    PRIORITY_INVALID: 'Priority must be low, medium, or high.',
    PROJECT_NAME_REQUIRED: 'Project name is required.',
    PROJECT_NAME_MAX: 'Project name must be 255 characters or fewer.',
    PROJECT_NAME_FORMAT: 'Project name can only contain letters, numbers, spaces, and hyphens.',
    BUDGET_REQUIRED: 'Budget is required.',
    BUDGET_FORMAT: 'Budget must be a whole number.',
    CATEGORY_REQUIRED: 'Select a category.',
    CATEGORY_INVALID: 'Category must be internal, external, or vendor.',
    TEAM_MEMBERS_REQUIRED: 'Select at least one team member.',
    TEAM_MEMBERS_INVALID: 'One or more team members are invalid.',
  },
  TOAST: {
    SUCCESS_TITLE: 'Success',
    ERROR_TITLE: 'Error',
    DISMISS: 'Dismiss',
    CREATE_SUCCESS: 'Resource created.',
    DELETE_SUCCESS: 'Resource deleted.',
    SAVE_BASIC_INFO_SUCCESS: 'Basic Info saved.',
    SAVE_PROJECT_DETAILS_SUCCESS: 'Project Details saved.',
    SUBMIT_CHANGES_SUCCESS: 'Changes saved.',
    PROVISION_SUCCESS: 'Resource completed.',
  },
  ERRORS: {
    LOAD_RESOURCES: 'Could not load resources.',
    CREATE_RESOURCE: 'Could not create resource.',
    DELETE_RESOURCE: 'Could not delete resource.',
    PROVISION_RESOURCE: 'Could not complete resource.',
    SAVE_BASIC_INFO: 'Could not save Basic Info.',
    SAVE_PROJECT_DETAILS: 'Could not save Project Details.',
  },
} as const
